name: Write blog post from article
description: Submit a new item
title: "[Blog] Write blog post: <Article Topic>"
labels: ["blog"]
assignees: [ "copilot" ]
body:
  - type: input
    id: url
    attributes:
      label: Reference Article URL
      description: Enter the URL of article(s) to base the blog post on
      placeholder: https://linkedin.com/pulse/...
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: Title
      description: A possible title for the blog post
      placeholder: How Operaton simplifies...

  - type: textarea
    id: addtional_context
    attributes:
      label: Additional Context
      description: Provide addtional instructions or context for the blog post
      placeholder: Consider to...
