name: Maintenance

on:
  workflow_dispatch:
    inputs:
      slack_url:
        description: 'Update Slack Invitation URL'
        type: string

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-slack-invitation-url:
    if: ${{ github.event.inputs.slack_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Slack Invitation URL
        run: |
          .devenv/scripts/maintenance/update-slack-link.sh ${{ github.event.inputs.slack_url}}
        shell: bash
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            index.html
            chat.md
          branch: maintenance/update-slack-invitation-url
          base: main
          title: "chore: Update Slack Invitation URL"
          body: "This PR updates the Slack Invitation URL on the website."

      #- name: Commit changes
      #  uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
      #  with:
      #    add: '["index.html", "chat.md"]'
      #    message: "chore: Update Slack Invitation URL"
      #    #default_author: github_actions
