name: Maintenance

on:
  workflow_dispatch:
    inputs:
      slack_url:
        description: 'Update Slack Invitation URL'
        type: string

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-slack-invitation-url:
    if: ${{ github.event.inputs.slack_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Update Slack Invitation URL
        run: |
          .devenv/scripts/maintenance/update-slack-link.sh ${{ github.event.inputs.slack_url}}
        shell: bash
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e #v7.0.8
        with:
          title: '[bot] Update Slack Invitation URL'
          commit-message: 'chore: Update Slack Invitation URL'
          branch: 'maintenance/update-slack-invitation-url'
          labels: maintenance
